### ISSUE TITLE
sc3_kmeans produces "Warning message: Quick-TRANSfer stage steps exceeded maximum (= 250000)"

### ISSUE THREAD

**Issue by MikeHala** [hemberg-lab/SC3#100]
Dear SC3 developers,

I am running SC3 (1.12.0) on HPC with a dataset with ~10k cells and ~ 17k genes.

Running the step sce <- sc3_kmeans(sce, ks = 10:25), after reaching 100% on the progress bar, it produces a bunch of 
Warning messages:
1: Quick-TRANSfer stage steps exceeded maximum (= 250000)
2: Quick-TRANSfer stage steps exceeded maximum (= 250000)
...

Is this just a warning that can be safely ignored or some intervention is needed?

Best,
Mike

**Comment by wikiselev** [comment]
Hi Mike, yes, I believe it can be ignored. Your dataset is quite large for SC3, remember it's an old horse!
