### ISSUE TITLE
Saving SC3 clustering output as csv files

### ISSUE THREAD

**Issue by bsamal20** [hemberg-lab/SC3#106]
I get beautiful graphs on gene expression, differential gene expression (DE) as well as marker genes marking each cluster. However, I would like to save these results as csv or Excel files to double-check with databases etc.

**Comment by mhemberg** [comment]
Thanks for your question. If you run SC3 in the non-interactive mode, I think it should be straightforward to extract this information as shown in the vignette: https://bioconductor.org/packages/release/bioc/vignettes/SC3/inst/doc/SC3.html#de-and-marker-genes

**Comment by bsamal20** [comment]
Working from the 'Yan' dataset was smooth. However, how do I use SC3 with my 10X Genomix data already normalized with Seurat, before or after running PCA?

**Comment by bsamal20** [comment]
Running SC3 using yan dataset goes smoothly. How can I run my 10X Genomix data normalized using Seurat before or after PCA?
