### ISSUE TITLE
 long vectors are not supported in .C

### ISSUE THREAD

**Issue by zhangtongda** [hemberg-lab/SC3#107]
Hello,

I get the following error message:
......................

Error in predict.svm(model, t(study)) :
  long vectors (argument 23) are not supported in .C
Calls: sc3_run_svm ... sc3_run_svm -> support_vector_machines -> predict -> predict.svm
Execution halted

**Comment by mhemberg** [comment]
I am not sure how to fix this, but for larger datasets I strongly recommend that you use the new version of SC3:

https://github.com/hemberg-lab/sc3s

Main downside is that it is for python rather than R, but the improved performance should more than make up for the hassle.
