### ISSUE TITLE
Running SC3 in integrated data

### ISSUE THREAD

**Issue by anemartinezlarrinaga2898** [hemberg-lab/SC3#109]
Hello! 

I wanted to ask if someone has tried to run SC3 in integrated data? 

Thanks!

**Comment by mhemberg** [comment]
When we developed SC3, none of the methods for batch integration existed, so it has not been thoroughly tested for this purpose. Many batch correction methods do not change the count matrix, but instead they operate on a latent space. Hence they are not really compatible with SC3 as it takes the count matrix as input. However, then ones that do modify the count matrix should in principle work well.
