### ISSUE TITLE
Question about <NA> labels from cell clustering via SC3

### ISSUE THREAD

**Issue by yxy92** [hemberg-lab/SC3#111]
Not sure if this is bug or more case-specific problem. I am using SC3 for cell clustering benchmark purpose, and when I tested it on a PBMC14K dataset with specified number of clusters k=7 from true labels. SC3 finishes clustering, with >50% of cells assigned with cluster label <NA>. There is no error message. How should I interpret this result or modify the argument running SC3. What causes <NA> from a consensus clustering?

**Comment by mhemberg** [comment]
Thanks for your request. Unfortunately, does not handle datasets with 14k cells very well, and as the software is no longer actively maintained, I do not think it is fair to include it in a benchmark. Instead, I advice that you use the new [SC3s](https://github.com/hemberg-lab/sc3s) version which was developed to handle larger datasets.
