### ISSUE TITLE
Add column colouring to sc3_plot_markers

### ISSUE THREAD

**Issue by kieranrcampbell** [hemberg-lab/SC3#30]
It would be really nice to have an additional argument passed to `sc3_plot_markers` that accepted either an N length vector (for N cells) or a column name of `pData(sceset)` that added column colouring to the resulting heatmap, so you can compare the consistency of the clustering with a known covariate.

**Comment by wikiselev** [comment]
Hi Kieran! Thanks for your suggestion, this is exactly what I am working on right now. In the next release you should be able to visualise any column from the pData(sceset) on the SC3 heatmaps.

**Comment by wikiselev** [comment]
This is now done. Please reinstall SC3 from GitHub (Bioconductor build might happen only next week). Updated manual is here: https://cdn.rawgit.com/hemberg-lab/SC3/master/vignettes/my-vignette.html

Thanks again for your suggestion!

Cheers,
Vlad

**Comment by kieranrcampbell** [comment]
Thanks, this is excellent.
Kieran
