### ISSUE TITLE
No 'dimnames' attribute for array

### ISSUE THREAD

**Issue by JRWK** [hemberg-lab/SC3#34]
Running SC3 on a dataset, post QC and normalisation. The clustering completes, followed by calc_biology, but upon attempting to plot_de_genes or plot_markers, I get the following error:

Error in dataset[names(de_genes), , drop = FALSE] : 
  no 'dimnames' attribute for array

The fData of the dataset is properly updated with markers_clusts, markers_padj, and de_padj columns, which leads me to believe that it might be a plotting error?

**Comment by wikiselev** [comment]
Hi, thanks for letting me know about this issue! Could you please share your SCESet (after running SC3) with me (vk6@sanger.ac.uk)? And also could you please send me the exact command you run, that produces an error? Additionally, I will also need an output of
```
library(SC3)
sessionInfo()
```

and

```
source("https://bioconductor.org/biocLite.R")
```

Many thanks,
Cheers,
Vlad

**Comment by wikiselev** [comment]
Hi John,

It looks like the information about sample names and gene names is lost in your SCESet object. For example, if you run:
```
exprs(regression_scran_sum)[1:3, 1:3]
```
you will see that neither columns nor rows have any names. This is a problem which shouldn't happen with default `scater` functions unless your overwrite the `exprs` slot manually.

Looking at your object name, I suppose you have performed `scran` normalisation, which had overwritten the `exprs` slot in your object, and the new matrix does not contain any names, therefore SC3 plotting functions don't work. In this case, this would be a `scran` bug. Or maybe lack of `scater` checks...

Could you please find out at which step of your analysis colnames and rownames of `exprs(regression_scran_sum)` disappear and then let me know? I have both developers of `scater` and `scran` here on campus and quickly contact them.

Cheers,
Vlad
