### ISSUE TITLE
column annotations and list of genes

### ISSUE THREAD

**Issue by dkoppstein** [hemberg-lab/SC3#41]
Hi, I have two feature requests: adding an option to include sample/column labels to the SC3 plots, and also having a separate method to visualize a list of genes of interest. I think I can implement this, would you accept a PR?

**Comment by wikiselev** [comment]
Hi David, 

Sure, please feel free to pull request any useful features you have in mind! We always appreciate contributions to our packages. Many thanks for your message.

Cheers,
Vlad
