### ISSUE TITLE
sc3_plot_silhouette generate an empty plot

### ISSUE THREAD

**Issue by yicheinchang** [hemberg-lab/SC3#45]
Hi,
I am applying SC3 on a big single cell RNAseq data set with about 3,000 cells and 27,000 genes. 

Running sc3 itself is OK.
```r
SC3 <- sc3(my_data, ks = 2:20, biology = TRUE, k_estimator = FALSE, pct_dropout_max = 95, gene_filter = TRUE, pct_dropout_min = 5)
```
However, I encounter several issues while generating the report.
First, the `sc3_plot_silhouette(SC3, k=5)` returned me an empty plot
![image](https://user-images.githubusercontent.com/5447168/32451628-4ae4e446-c2e5-11e7-854a-f4b8eae47087.png)

The plot is still 'informative' since the silhouette width of each cluster and the average silhouette width are still visible. If `sc3_plot_silhouette` can not handle the large data set, is there an easy way to get rid of the blank silhouette?

Thanks in advance.

## session info
- R version 3.4.2
- Bioconductor 3.6
- scater_1.6.0
- SC3_1.6.0

**Comment by wikiselev** [comment]
Hi, thanks for reporting this! Are you working in RStudio? I have the same problem in RStudio, however, if I try to plot it to a file (using e.g. `pdf` function) or from a terminal, everything looks ok. Could you please confirm that you can reproduce this? Many thanks in advance. Vlad

**Comment by yicheinchang** [comment]
Confirm!!
This plot function works in R console but not in RStudio and in RMarkdown.
Thanks !!! @wikiselev
