### ISSUE TITLE
Is it safe to just replace all reference to SCESet with SingleCellExperiment?

### ISSUE THREAD

**Issue by Shians** [hemberg-lab/SC3#48]
A lot of the documentation still references SCESet, could these all just be replaced with SingleCellExperiment since SCESets are deprecated?

**Comment by wikiselev** [comment]
Hi, yes, sorry, I haven't had time to update the documentation yet, just did the vignette. I will try to do that in the next couple of weeks.

**Comment by wikiselev** [comment]
Many thanks for this help!
