### ISSUE TITLE
Color changing of heatmap annotation (sc3_plot_consensus & expression, etc..)

### ISSUE THREAD

**Issue by jy-nam** [hemberg-lab/SC3#54]
Hi!

Can I change the colors of specific pdata in heatmap manually?
I want to fix my sample label color.

Thanks!
JY

**Comment by wikiselev** [comment]
@jy-nam sorry for a delayed response. For the heatmaps we are using the `pheatmap` package with some default values. At the moment, I don't think it is possible to change them.

**Comment by carogrou** [comment]
Hello,
I was just wondering if any changes had been made in regards to this or if it is still not possible to change the colors for pdata annotations in SC3 heatmaps?
Thanks

**Comment by wikiselev** [comment]
Hi, sorry, unfortunately there is no one working on SC3 development at the moment and we are not planning to invest more time in it mainly because it does not scale well with the experiment sizes nowadays. We expect to be used less and less.

**Comment by carogrou** [comment]
Ok i see. Thank you very much for the information
