### ISSUE TITLE
sc3_plot_de_genes duplicate row names

### ISSUE THREAD

**Issue by koelling** [hemberg-lab/SC3#55]
Maybe I am doing something wrong, but for some values of k I am getting the following error when calling `sc3_plot_de_genes`:

```
Warning message:
“non-unique value when setting 'row.names': ‘Lilrb4a’”
Error in `row.names<-.data.frame`(`*tmp*`, value = value): duplicate 'row.names' are not allowed
Traceback:

1. sc3_plot_de_genes(sce_named, k = k)
2. sc3_plot_de_genes(sce_named, k = k)
3. `rownames<-`(`*tmp*`, value = names(de_genes))
4. `row.names<-`(`*tmp*`, value = value)
5. `row.names<-.data.frame`(`*tmp*`, value = value)
6. stop("duplicate 'row.names' are not allowed")
```

Is it possible that there is a bug somewhere, maybe if a gene is called as differentially expressed for multiple clusters somehow?

**Comment by koelling** [comment]
I'm using SC3_1.7.6

**Comment by wikiselev** [comment]
@koelling sorry for a delayed response, have you figured the problem? If not, could you please share your dataset with vk6@sanger.ac.uk?
