### ISSUE TITLE
export plot from SC3

### ISSUE THREAD

**Issue by MichaelPeibo** [hemberg-lab/SC3#62]
Hi, SC3 team
Nice package to explore!
I got this issue:

I am using R in ubuntu by terminal,
`> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.7 (Final)
`
 so when I export the plot, usually I use this code:
`pdf('sc3 marker genes.pdf')
sc3_plot_markers(SC3.test, k = 23,show_pdata ="sc3_23_clusters")
dev.off()`
I got plot like this, which is uncomplete
[sc3 marker genes.pdf](https://github.com/hemberg-lab/SC3/files/1778480/sc3.marker.genes.pdf)
how should I deal with it?

**Comment by wikiselev** [comment]
Hi, try to increase the height of the page in the `pdf` call. See `?pdf` for more details.

**Comment by MichaelPeibo** [comment]
Right! Increasing height works! Thanks!

**Comment by MichaelPeibo** [comment]
Right! Increasing height works! Thanks!
