### ISSUE TITLE
default for `n_cores`

### ISSUE THREAD

**Issue by stephaniehicks** [hemberg-lab/SC3#63]
Hi Vlad, 

This is less of an _issue_ and more of a suggestion, but wasn't sure where to put it. I was using SC3 and noticed the default for `n_cores` in `sc3()` function is to use `n_cores <- parallel::detectCores()` if `n_cores` is left NULL in the function (https://github.com/hemberg-lab/SC3/blob/master/R/CoreMethods.R). I checked the vignette and didn't see a mention of how the parallelization works. It would be useful to mention that in the vignette that the default is to grab all the cores available using `parallel::detectCores()` as a heads up. 

The problem I ran into is I assumed leaving the `n_cores=NULL` default meant only 1 core would be used, unless I specify more. When I was running this on the cluster when just asking for 1 core, `sc3()` was grabbing way more than that causing troubles with my cluster admin. 

Thanks
Stephanie

**Comment by wikiselev** [comment]
Hi Stephanie,

Many thanks for your suggestion. I've added notes in both the vignette and the docs and just pushed it to GitHub (https://github.com/hemberg-lab/SC3/commit/bc2ffd0f3a1cd380e3c77f54ade4d4c55ce8e70c) and the devel branch.

Cheers,
Vlad
