### ISSUE TITLE
Feature request: option to specify assay used

### ISSUE THREAD

**Issue by dkoppstein** [hemberg-lab/SC3#66]
Currently, SC3 defaults to using logcounts in a SingleCellExperiment. However, often you want to keep the raw logcounts data separate from batch-corrected or TMM-normalized data, i.e. using limma or ComBat and then assigning it to the norm_exprs value (or some other assay). It would be useful to have an additional option to specify the assay used from the SingleCellExperiment object, similar to `scater::runPCA`'s `exprs_values` argument.

**Comment by wikiselev** [comment]
Hello, thanks for your request! The easiest would be to write whatever you would like to use for clustering into the `logcounts` slot. We used to have the `exprs_values` argument but stopped using it at some point as it was not easy to deal with all possible scenarios. Hope it helps.

**Comment by alfonsosaera** [comment]
I also think adding something similar to the`scater::runPCA`'s `exprs_values` argument would allow for more flexibility when using the package.
Thanks!

**Comment by pati-ni** [comment]
@wikiselev it would be possible to specify an assay during initialization. However if nothing is specified I think the current behavior is fine.

**Comment by wikiselev** [comment]
@pati-ni you can try, but I remember the way I wrote it originally does not allow it to be flexible for this parameter...

**Comment by wikiselev** [comment]
@pati-ni has also left, so I don't think this will be implemented. You are welcome to create a pull request, but if not, please use the `logcounts` slot for what you want to achieve.
