### ISSUE TITLE
 Error in checkForRemoteErrors(val) :    

### ISSUE THREAD

**Issue by 15084921898** [hemberg-lab/SC3#72]
Hi, i am using SC3 by executing the R script in the SC3-master/R folder ,instead of library SC3 package.
I am getting errors after running the code as follow:
main code
_**usos <- sc3(usos, ks = 3, biology = FALSE,gene_filter = FALSE)**_

When running code 
{# calculate distances in parallel
    dists <- foreach::foreach(i = distances) %dorng% {
        try({
          calculate_distance(dataset, i)
        })
    }}

errors as:
 Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: Error in calculate_distance(dataset, i) : 
  no function "calculate_distance"

Thank you!

**Comment by wikiselev** [comment]
Hi, I think you need to install `SC3` properly, otherwise I can't really guarantee it's behaviour.

**Comment by bluesea0** [comment]
I have met the same problem. Did you have ever solve it?
