### ISSUE TITLE
Error in checkForRemoteErrors(val) : 3 nodes produced errors; first error: Error in ED2(data) : Not compatible with requested type: [type=S4; target=double].

### ISSUE THREAD

**Issue by JesusCorria** [hemberg-lab/SC3#74]
Hello 

I was running SC3 and I got the following error Error in checkForRemoteErrors(val) : 3 nodes produced errors; first error: Error in ED2(data) : Not compatible with requested type: [type=S4; target=double].

How Can I solve it?

Thanks in advance

Jesus

**Comment by pati-ni** [comment]
Can you check if your gene expression matrix you use is sparse? 
`is.matrix(yourcountassay(sce))`

**Comment by JesusCorria** [comment]
Thanks 

I realize that was the problem and I solved it , 

My best wishes

Jesús
