### ISSUE TITLE
Specify custom genes/features

### ISSUE THREAD

**Issue by royfrancis** [hemberg-lab/SC3#78]
It's not very clear to me where is the sc3 workflow the feature selection happens. I have a list of highly variable genes that I would like to use for the sc3 clustering. Where/when do I specify this?
Thanks.

**Comment by wikiselev** [comment]
Hi, yes, you can manually define genes that you want to use for clustering by setting the `sc3_gene_filter ` column of the `rowData` slot. See some more description [here](https://bioconductor.org/packages/release/bioc/vignettes/SC3/inst/doc/SC3.html#rowdata). You can do:
```
rowData(sce)$sc3_gene_filter <- ... (a boolean vector with the selected genes corresponding to TRUE)
```
