### ISSUE TITLE
Which data type for clustering

### ISSUE THREAD

**Issue by mkrzak** [hemberg-lab/SC3#85]
Hi,

I have a question concerning the type of counts that are favorable for SC3 clustering. In the example there are log transformed FPKM . Do you think that method would work well with raw counts, UMIs or CPM ?

Best,
Monika

**Comment by wikiselev** [comment]
Hi Monica, sorry for a late reply. SC3 will work with anything (but without negative values) you give it, but it is recommended to do a library size normalisation and log transformations for most of the scRNAseq methods.

Very sorry for such a late reply.

**Comment by mkrzak** [comment]
Dear @wikiselev 
Thank you very much for your answer, it is still useful for me.
Best,
Monika
