### ISSUE TITLE
How to calculate D?

### ISSUE THREAD

**Issue by XiHuYan** [hemberg-lab/SC3#91]
Hello, I'm a student interested in Machine learrning. After reading the paper of SC3, I'm confused about the parameters d and D.  Is d  a constant or a range in the process of running the algorithm? If d is a constant, how is the value of D calculated? If d is a range, how do you calculate the range of d when the model is trained? Thanks for answering it.

**Comment by wikiselev** [comment]
Hi, d is a range, and D is a maximum index in d range. There is no training happening in the SC3 algorithm. Hope this helps.

Cheers,
Vlad

**Comment by XiHuYan** [comment]
Thanks for reply. But I'm still a bit confused. The SC3 paper mentions that di (d1,d2,...dD) is a matrix composed of multiple feature vectors extracted from the feature vector of transformation martics of PCA or Laplacian. Then, are these feature vectors d1,,,dD gradually accumulated, or are there any intersections?

**Comment by wikiselev** [comment]
Clustering is performed for each d1,,,dD matrix of eigenvectors and then the results are averaged using the consensus approach.

**Comment by XiHuYan** [comment]
Thanks for your patience and answering.
