### ISSUE TITLE
SC3 with Batch Correction

### ISSUE THREAD

**Issue by hkarakurt8742** [hemberg-lab/SC3#92]
Hello,
I want to use SC3 for data sets from multiple batches. I use fastMNN() function of Scran package for batch normalization but it does not effect logcounts, it just creates a reduced dimension "MNN" that shows the corrected data.
How can I use SC3 with these values? Can I create a new SingleCellExperiment with MNN matrix and use SC3 on that matrix? MNN matrix includes negative values so I know I should not use gene_filter parameter as TRUE.

Thank you in advance.

**Comment by wikiselev** [comment]
Hi, you can always copy your corrected matrix to logcounts, so no need to create a new object. Or if you care about logcounts, then yes, it would be a good idea to create a separate object.

However, I think SC3 won't work well with negative values (as majority of other scRNAseq methods), so cannot guarantee a good result.
