### ISSUE TITLE
Clustering for more than 10000 Genes

### ISSUE THREAD

**Issue by hkarakurt8742** [hemberg-lab/SC3#93]
Hello,
As I know for data sets which contain more than 5000 cells, SC3 uses a hybrid approach (SVM). 
If a data set contains more than 10000 (let's say 12000), are randomly selected 5000 cells enough for this approach?
Because randomly selected cells may not involve some cell types in this situation (I am not sure about probability) so with SVM, these cells will assigned to only cell which are used for training data.

**Comment by wikiselev** [comment]
Sorry, are you asking about genes or cells, it's not clear from your question? SC3 does not select random genes, but it does select random cells.

**Comment by hkarakurt8742** [comment]
> Sorry, are you asking about genes or cells, it's not clear from your question? SC3 does not select random genes, but it does select random cells.

I am sorry I wrote it wrong. I edited it.
I meant cells not genes.

**Comment by wikiselev** [comment]
Yes, this is correct, using the SC3 approach you may miss some rare cell type. For a large number of cells we recommend using other clustering tools such as Seurat or scanpy.
