### ISSUE TITLE
Which remove-batch-effect package work best with SC3?

### ISSUE THREAD

**Issue by kuang-da** [hemberg-lab/SC3#99]
Hi,
Thanks for providing such nice work! It seems that SC3 only works with positive numbers but the corrected matrices from Harmony or Scanorma almost always contain negative values. May I ask what would be a good practice to remove the batch effect before applying SC3? Thank you very much!

**Comment by mhemberg** [comment]
Hi,
we recently addressed this question in a preprint that you can find [here](https://www.biorxiv.org/content/10.1101/2020.05.22.111211v2). The short answer is that there was not a single method that always performed best as you can see from fig 5a.

In terms of your original question, SC3 works well when there are negative entries in the expression matrix as all the clustering is done on the distance or Laplace matrix.
